image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8

before_script:
  - bundle install --full-index

pages:
  stage: deploy
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
      - _site
  only:
    - master
