# Meta
title: Richard-von-Weizs채cker-Gymnasium Baiersbronn
author: Felicitas Pojtinger
email: felicitas@pojtinger.com
lang: de
description: >-
  Webseite des Richard-von-Weizs채cker-Gymnasiums in Baiersbronn.
keywords:
  - RvWG
  - RvWG Cloud
  - RvWG Nextcloud
  - RvWG Mensa
  - Baiersbronn
  - Gymnasium
  - SWAG
  - Sch체ler-Website-AG
  - G8
  - Richard von Weizs채cker
  - Oberdorf
  - Freie Software
  - Open Source
  - AGPL-3.0

# Config
url: https://www.rvwg.tk
