# Meta
title: Richard-von-Weizs채cker-Gymnasium Baiersbronn
author: Felicitas Pojtinger
email: felicitas@pojtinger.com
lang: de
description: >-
  Webseite des Richard-von-Weizs채cker-Gymnasiums in Baiersbronn.
keywords:
  - Baiersbronn
  - Gymnasium
  - SWAG
  - Sch체ler-Website-AG
  - G8
  - RvWG
  - RvWG Cloud
  - RvWG Nextcloud
  - Richard von Weizs채cker
  - Oberdorf
  - Nextcloud
  - Freie Software
  - Open Source
  - AGPL-3.0

# Config
baseurl: ""
url: https://www.rvwg.tk/
defaults:
  - scope:
      path: ""
    values:
      layout: default
collections:
  pages:
    output: true
    permalink: /:path.html

# Plugins
plugins:
  - jekyll-pwa-plugin
  - jekyll-gzip

# Progressive Web App
pwa:
  sw_src_filepath: js/service-worker.js
  dest_js_directory: assets/js
